### PR TITLE
Use `addenv` to ensure git commands don't leak env variables

### PR DESCRIPTION
**Pull request by giordano**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Want to add a `depwarn` for the function or functions that should be deprecated?

Then, in the not-so-distant future, we can make a breaking release of GitCommand in which we have removed those functions.

**Comment by giordano** [comment]
> Want to add a depwarn for the function or functions that should be deprecated?

The fact is that the way you call the function is completely different, not sure how to write a reasonable deprecation warning

**Comment by DilumAluthge** [comment]
> > Want to add a depwarn for the function or functions that should be deprecated?
> 
> The fact is that the way you call the function is completely different, not sure how to write a reasonable deprecation warning

Ah fair enough, yeah let's omit the depwarn then.

**Comment by DilumAluthge** [comment]
Honestly the new interface looks much easier to use!

**Comment by giordano** [comment]
Ok, well, tests are passing also on Windows.  I guess it's good, but then I don't understand what's going on in https://github.com/giordano/AnalyzeRegistry.jl/pull/39.  Marking this as ready for review

**Comment by DilumAluthge** [comment]
What's the Windows issue you're having? IIRC on Windows we just distribute the official Git for Windows binaries. So on Windows I don't think we do any modification of the environment, or the library search path, or anything like that.

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
LGTM.

I can't believe that before this PR I was doing things like `copy(ENV)` 😱

**Comment by giordano** [comment]
> What's the Windows issue you're having? 

The environment variables seem to be leaked: https://github.com/giordano/AnalyzeRegistry.jl/pull/39/checks?check_run_id=2161991335#step:6:134.  But tests here don't confirm it

**Comment by DilumAluthge** [comment]
Maybe something is going wrong inside Git_jll? IIRC on Windows we get the environment variables mappings straight from Git_jll: https://github.com/JuliaVersionControl/GitCommand.jl/blob/64d6cff67b2fe3f7050d8108183139ecd3ab4f58/src/env.jl#L4

**Comment by DilumAluthge** [comment]
But also, on Windows, we read some stuff from the existing `ENV`... perhaps that is not thread-safe?

**Comment by giordano** [comment]
> But also, on Windows, we read some stuff from the existing `ENV`... perhaps that is not thread-safe?

Reading isn't 100% thread-safe if something else is changing the global variables, but the important thing is that _we_ don't changes the global state, which is what I'm ensuring with the added tests.  And we read `ENV` also in the other operating systems
https://github.com/JuliaVersionControl/GitCommand.jl/blob/64d6cff67b2fe3f7050d8108183139ecd3ab4f58/src/env.jl#L31

**Pull request merged**
